version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file: ./backend/.env
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:grid2home@db:5432/farfetchr
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: bash -c "./wait-for-it.sh db:5432 -- python init_db.py && uvicorn main:app --host 0.0.0.0 --port 8000"

  frontend:
    build: .
    ports:
      - "4173:4173"
    depends_on:
      - backend

volumes:
  pgdata: 